# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion="[13,)" #mandatory

# A text field displayed in the mod UI
credits="Guichaguri for the original mod and FalseHonesty for making & maintaining the mod for 1.13+" #optional

# A text field displayed in the mod UI
authors="FalseHonesty" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="tickratechanger" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="2.0" #mandatory

# A display name for the mod
displayName="TickrateChanger" #mandatory

# The description text for the mod (multi line!) (#mandatory)
description='''
Tickrate Changer is a mod that allows the user to change the tick speed of the game.
The original mod was created by Guichaguri, and was ported to 1.13 by FalseHonesty.
'''